import = [
       "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[shell]
program = "/bin/bash"
args = ["--login"]

[font]
normal = {family = "FiraCodeNerdFontMono", style="Regular"}
bold = {family = "FiraCodeNerdFontMono", style="Bold"}
italic = {family = "FiraCodeNerdFontMono", style="Italic"}
bold_italic = {family = "FiraCodeNerdFontMono", style="Bold Italic"}
