import = ["/home/choneyfox/.config/alacritty/colors.yml", "/home/choneyfox/.config/alacritty/fonts.yml"]
live_config_reload = true

[shell]
program = "/usr/bin/fish"
args = ["--login"]

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
#history = 10000
#multiplier = 3
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 5
y = 3
