[colors.bright]
black = "0x4a697d"
blue = "0x51b4ff"
cyan = "0x5cdff0"
green = "0x70d675"
magenta = "0xc979d7"
red = "0xfb8784"
white = "0xffffff"
yellow = "0xffe744"

[colors.normal]
black = "0x263640"
blue = "0x42a5f5"
cyan = "0x4dd0e1"
green = "0x61c766"
magenta = "0xba68c8"
red = "0xec7875"
white = "0xfff000"
yellow = "0xfdd835"

[colors.primary]
background = "0x212B30"
foreground = "0xc4c7c5"
